### ISSUE TITLE
Don't use metric grid on the schematic

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#14]
Industry standard unfortunately is 100 mil grid. All the symbols are designed for it. Using different grid can cause issues with things not aligning with each other.

On the PCB it's better to use metric grid.

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/203382586-c83b73cf-7f03-41f0-8d01-79de9738a472.png)

There are a lot of "Off grid" warnings:
![image](https://user-images.githubusercontent.com/1595938/203382744-4cb7ff4a-a084-416c-872e-a2fa4d878548.png)

Use 100 mil grid and place all schematic object to that grid.

You can set grid to 100 mil (toggle grid with G), select objects on the schematic, use Edit -> Align -> Align To Grid (Shift + Ctrl + D) and adjust manually as necessary.

If symbols were not created with 100 mil grid, then the symbols also need to be changed.

**Comment by ReikoR** [comment]
Move schematic objects to 100 mil grid.

One part of the schematic with misalignement:
![image](https://user-images.githubusercontent.com/1595938/204629223-97c4952f-661e-4d69-b320-c101023c473d.png)

**Comment by markus-marandi** [comment]
done

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/205438379-24492ad6-3504-43fe-89b0-88ee8c26ccc0.png)
![image](https://user-images.githubusercontent.com/1595938/205438395-3b2c99aa-3d3e-4ee4-be4f-90b986cf6145.png)
![image](https://user-images.githubusercontent.com/1595938/205438432-672ed348-dacf-49f4-93d4-95f388bfe1c3.png)
![image](https://user-images.githubusercontent.com/1595938/205438466-974cc863-d5d5-4818-9568-c94f1dc1d606.png)

**Comment by markus-marandi** [comment]
fixed

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/205489368-4fe4497b-8c9a-416e-b988-0c037938d605.png)
![image](https://user-images.githubusercontent.com/1595938/205489427-e98f5e01-251a-4379-969f-7fabb31705d7.png)
![image](https://user-images.githubusercontent.com/1595938/205489474-236da63c-5c79-4b8e-809b-439cc59e447a.png)

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205506134-0f780839-97bc-40ab-9c94-02c8cc9bfab6.png)
![image](https://user-images.githubusercontent.com/75824680/205506158-f656ddad-f467-4082-8cdf-f575f5860e95.png)
![image](https://user-images.githubusercontent.com/75824680/205506174-3cfe8d2a-83a1-4a95-b253-d7dfbafa8e3e.png)

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205589105-745af7d6-62a0-4923-945f-7ea8e38ee0bb.png)
![image](https://user-images.githubusercontent.com/75824680/205589214-d8dd68c0-2cfb-4b38-a5e3-5824c6e3fb8c.png)
![image](https://user-images.githubusercontent.com/75824680/205589397-1ab8f458-8005-4ce9-8002-f49bc0c815f3.png)
![image](https://user-images.githubusercontent.com/75824680/205589581-ddf93ac8-0602-4298-a250-7dee288c2e1c.png)
![image](https://user-images.githubusercontent.com/75824680/205590064-a7b12987-e004-450e-b141-bacd69a13cb1.png)
