### ISSUE TITLE
[Mechanics] how easy was it to assemble?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#25]
Overall it seems file but I would have suggested an hourglass shape here for simpler assembly:

![image](https://user-images.githubusercontent.com/5435954/201516790-0a9c0f56-e3f5-4d13-a1b3-94c2d0e4454f.png)

**Comment by ToxaRyd** [comment]
Well, the force needed, though not difficult, may be problems with disassembling but still I a small problem to get rid of extra assembling operation and production of pcb plate to hold the bearings...
