### ISSUE TITLE
[Mechanics] make a hole for the shaft

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#26]
I suggest making a hole for the motor shaft so the wheel can be mounted closer to the motor:

![image](https://user-images.githubusercontent.com/5435954/201516845-ec6b95e5-5a6f-499b-b731-025a9075e195.png)

![image](https://user-images.githubusercontent.com/5435954/201516880-ef1b451b-21ce-430e-a165-9bb747c50e81.png)

**Comment by ToxaRyd** [comment]
Done
