### ISSUE TITLE
Use switching regulator instead of linear regulator for servo power

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#30]
![image](https://user-images.githubusercontent.com/1595938/203390970-f10816f9-4cbf-4678-ad52-49c8024cdaa2.png)
![image](https://user-images.githubusercontent.com/1595938/203390996-a0a8f222-823d-4d78-af1d-c01668ca2578.png)

Linear regulators are too inefficient for higher currents.

We have these components available in the lab:

- XTPS62933DRLR (TPS62933 buck converter)
- SRP6060FA-5R6M (Inductor 5.6uH 10A)

You can use TI WEBENCH to get recommended designs for TI components:
https://webench.ti.com/power-designer/switching-regulator

**Considering that there is not too much time left to complete the design, I would recommend not adding servo connection and continuing with a simpler design.**

**Comment by markus-marandi** [comment]
removed servo NCV and 215079-4 components

**Comment by ReikoR** [comment]
If you're not using servos, then remove switching regulator and use linear regulator (NCV8730).

Isolators don't need high current and layout of NCV8730 is much simpler.

**Comment by markus-marandi** [comment]
added ncv8730

**Comment by ReikoR** [comment]
There is no 3.3V regulator any more.
And switching regulator (TPS62933) is still there.

**Comment by markus-marandi** [comment]
removed TPS62933 and added ncp164
![image](https://user-images.githubusercontent.com/75824680/205507887-5a05a62c-08d3-4125-a042-13d87e03a13e.png)

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205507897-ab0e9f35-862d-4e00-b880-dcf718901f0f.png)

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/205567086-ad4a9044-679c-4d18-8d80-0a47a21d2c7c.png)

Add more input and output capacitance to NCP164.

From [NCP164 datasheet](https://www.onsemi.com/pdf/datasheet/ncp164-d.pdf):
> **Input Decoupling (C<sub>IN</sub>)**
> It is recommended to connect at least 1 uF ceramic X5R or X7R capacitor between IN and GND pin of the device.

> **Output Decoupling (C<sub>OUT</sub>)**
> The device is designed to be stable with standard ceramics capacitors with values of 1 uF or greater.
