### ISSUE TITLE
Add a spacer to the front of the thrower

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#31]
I suggest adding a 45 mm spacer to the front. This increases thrower rigidity but also protects the motor from crashes. Maybe the motor cable angel could also be changed a little so it does not point directly outwards

**Comment by ToxaRyd** [comment]
Done)

**Comment by Akustav** [comment]
With the current implementation I also suggest rotating the motor so the cable is not routed from the front of the robot. This can damage the cables when hitting something.

![image](https://user-images.githubusercontent.com/5435954/204161408-8f59e990-fffa-4791-ac08-84e40ab6643b.png)

**Comment by ToxaRyd** [comment]
done
