### ISSUE TITLE
Wider taper at the front of the robot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#32]
I suggest having a wider taper at the front of the robot. This reduces the required accuracy for aiming the ball. Also dont forget that the ball is round so the tapered front should make contact with the ball from around its center, else the ball might make a yanky motion, when it reaches the thrower

![image](https://user-images.githubusercontent.com/5435954/204077834-6354165c-474b-49b5-9b1e-6047a1ba11ce.png)

**Comment by ToxaRyd** [comment]
Yep I was thinking about that so made those wider, the thing I was concerned about is that the ball may be pressed early, towards the wall..but I will make it as you has shown

**Comment by ToxaRyd** [comment]
Seems to be done, waiting for approval
