### ISSUE TITLE
More support for camera legs

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#34]
I suggest a little more support for the camera legs since they can wobble about, when the robot is is motion. The slots do not help. Maybe add a plate to the middle of the legs?

![image](https://user-images.githubusercontent.com/5435954/204078084-948785d7-9d89-429e-91cc-db41df2718a5.png)

**Comment by ToxaRyd** [comment]
Yeah, I planned to add there a plane, I just have not finished yet)

**Comment by Akustav** [comment]
I see something added. How do you plan to fasten it. Additionally how do you plan to manufacture it?

![image](https://user-images.githubusercontent.com/5435954/204161286-1e7291a2-e2f9-4de2-a9b5-4b27994e0382.png)

**Comment by ToxaRyd** [comment]
3d printing, cause it is just rigid component, no fixing needed, maybe just position fix through the adjustment of the holes in the camera legs

**Comment by Akustav** [comment]
Some force needs to hold it in place, no? If it is just rattling there, there is little rigidity and support it is adding. If it were somewhat wider and was squeezed between the two legs, then maybe it can be a friction fit.

**Comment by ToxaRyd** [comment]
please check the newer version
