### ISSUE TITLE
Underdefined sketch

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#36]
The sketch is underdefined for the camera legs.

![image](https://user-images.githubusercontent.com/5435954/204078207-75e2acfe-73d8-464d-8b28-0b76e3668d9f.png)

Also... This camera leg reminds me an awful lot of the mount used by this robot. whats up with that:

![image](https://user-images.githubusercontent.com/5435954/204078298-6428b1a5-e149-41b8-a510-1dc56b933f8a.png)

**Comment by ToxaRyd** [comment]
defining sketches fully is a highly time consuming habit especially when smth needs to be redone, also I have never experienced any problems with that throughout 6 years of CAD exp...

**Comment by ToxaRyd** [comment]
Speaking of those mount slots, I may redo the entire leg to be thinner at those places by reducing the mount slots...

**Comment by Akustav** [comment]
Fully defining sketches is a good practice. Currently this sketch looks like a carbon copy-paste from the previous years robot that borders on plagiarism with its distinct features.

A side-to-side here:

![image](https://user-images.githubusercontent.com/5435954/204162577-a8ba4982-2d7e-4052-937b-6ba197e02b05.png)

**Comment by ToxaRyd** [comment]
Indeed the initial sketch was copy pasted from the test model given to my team, further - modified much. The reason - is simply saving time in terms of defining all the dimensions and of course, saving all angles to eliminate any extra job to be done for my team, if to speak about those mounting holes - I did find them very useful when additional electronics need to be fixed somewhere...
