### ISSUE TITLE
Cameras RGB sensor is not centered on the robot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#37]
The RGB sensor is not centered:

![image](https://user-images.githubusercontent.com/5435954/204161478-23704f62-43e9-4f20-bc09-f6ebca53c524.png)

Additionally there is no FOV cone to check if the cameras location is good.

**Comment by ToxaRyd** [comment]
about FOV con - I have leaved all parameters (height at least and camera plate holder angle) the same as in the old one, I was thinking to eliminate any possibilities for my team to redo calibration in their SW and waste time on it, so the camera location is good, except is that RGB camera is not centered yet...

**Comment by Akustav** [comment]
Would be good to see that the current thrower to camera location is good or did that also not change?

**Comment by ToxaRyd** [comment]
hard to remember, but any minor changes won't change much in that respect

**Comment by ToxaRyd** [comment]
donedonedone
