### ISSUE TITLE
Electronics board, switches and plugs missing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#38]
I can not find any PC power plugs, switches or similar on the robot. Also if you want to use moutnable XT-60 sockets like these, we have them in the lab.

![image](https://user-images.githubusercontent.com/5435954/204161636-ad09b533-8229-4588-a1fa-1b85654e5b37.png)

**Comment by ToxaRyd** [comment]
All electronics is located near to the rear wheel, all the connections are gonna be made as in the test robot - in air
