### ISSUE TITLE
[Mechanics] underdefined sketches

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#4]
There are currently under-defined sketches:
![image](https://user-images.githubusercontent.com/5435954/193413819-0cc008be-9d83-443b-a06b-e82368f5ca0d.png)

This can lead to unpredictable changes in model features when another sketch is changed. You should add dimensions until sketches turn black.

**Comment by ToxaRyd** [comment]
Did my best but errors of over constrain occur...

**Comment by Akustav** [comment]
Hm, currently seems fine to me. Overall when it gives you over-defined warnings, it means that you added multiple different dimensions to the same area. Usually the simplest way to see what is undefined is to take the sketch and try dragging some blue lines around. This shows you what elements start moving.
