### ISSUE TITLE
Camera USB port blocked by wall

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-snax#41]
The camera wall is blocking the USB port of the camera.
You can make a cutout on the side of the wall to make room for the USB.

![Fusion360_2022-11-28_15-04-41](https://user-images.githubusercontent.com/32770145/204287377-05637661-660d-4c4a-9e23-18b584dd3729.png)

**Comment by ToxaRyd** [comment]
its not, but anyway everything was about to be redone anyway)
