### ISSUE TITLE
Motor mount dogbones not millable

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-snax#44]
The dogbones of the motor mounts' tenons are not millable because a 3 mm mill wont be able to pass through the gap of the dogbones.
Making the dogbones like the red line can also give more support to the sides of the tenons of the motor mount.

![Fusion360_2022-11-28_15-13-30](https://user-images.githubusercontent.com/32770145/204288940-d31a3611-d02a-4b6c-ac2c-42b750ee08ff.png)

**Comment by ToxaRyd** [comment]
fixed
