### ISSUE TITLE
Camera holder wall dogbones not millable

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-snax#45]
The dogbones on the bottom of the camera holder wall are not millable due to both the current position of the dogbones and the hole size.

![pilt](https://user-images.githubusercontent.com/32770145/204629425-41605cf9-aeb1-407b-81a4-398c3051d094.png)

**Comment by ToxaRyd** [comment]
done?!

**Comment by Akustav** [comment]
One note here is that they can technically also be drilled but it takes a little more time with such a small drill and with the tool changes required

**Comment by ToxaRyd** [comment]
Done
