### ISSUE TITLE
Reverse voltage protection MOSFET connected incorrectly

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#48]
![image](https://user-images.githubusercontent.com/1595938/204633443-c2ff84fc-ce35-4120-9409-111ecc92759d.png)

Gate needs to be connected to GND.

**Comment by markus-marandi** [comment]
done

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/205438625-b717b7e4-b013-4c76-be84-4a3aae7b9291.png)

* Gate (G) needs to be connected to GND.
* Source (S) needs to be connected to +16.8.
* Bat- needs to be connected to GND.

Don't add additional labels to wires connected to power port. Power port already assigns a net name.
![image](https://user-images.githubusercontent.com/1595938/205438734-2b005f92-d6a4-4056-a9dc-1456eda14134.png)

**Comment by markus-marandi** [comment]
corrected connections

![image](https://user-images.githubusercontent.com/75824680/205463401-a95cf43f-e769-4887-8fad-f744604404ba.png)
