### ISSUE TITLE
NCV8730 input connected incorrectly

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#50]
![image](https://user-images.githubusercontent.com/1595938/204635529-4c231329-36be-4b21-b3fe-76971fd9ef47.png)

+16.8 needs to be connected to IN pin.
Input capacitor needs to be between +16.8 and GND.

**Comment by markus-marandi** [comment]
removed this component

**Comment by ReikoR** [comment]
Use NSV8730 instead of switching regulator.

See https://github.com/ut-robotics/picr22-team-snax/issues/30#issuecomment-1336138949

**Comment by markus-marandi** [comment]
added ncv8730 back
