### ISSUE TITLE
DRV8243 DRVOFF incorrectly connected

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#51]
![image](https://user-images.githubusercontent.com/1595938/204636298-6cceb1a2-c9cb-4f1c-b9fc-3c3e3f8b3fb9.png)

DRVOFF pin should not be connected to ITRIP pin.

**Comment by markus-marandi** [comment]
done

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/205439003-ef4f5756-de39-4a93-aca0-5583a487e2d2.png)

100k resistor needs to be connected to ITRIP pin to configure threshold voltage for current limiting.

**Comment by ReikoR** [comment]
DRVOFF pin can be connected straight to GND without any resistors.
`DRV_OFF_OUT` net label can be removed. Currently all DRVOFF pins would be connected together.

![image](https://user-images.githubusercontent.com/1595938/205490610-5e6bf73c-0b43-426e-a891-839d2a312fbf.png)

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205508083-f3600e7c-3f68-4d72-ab07-f7e1624f2a8c.png)
