### ISSUE TITLE
Use 0603 resistors

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#52]
![image](https://user-images.githubusercontent.com/1595938/204636694-42c15b58-477c-4085-9f74-6654b24ed90b.png)

Resistors available in the lab are in 0603 package.

**Comment by markus-marandi** [comment]
done

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/205439216-1b3fbe84-ba08-4a1a-a8c8-45a1c976ea61.png)

**Comment by markus-marandi** [comment]
fixed
