### ISSUE TITLE
Incorrect MAX14930DASE+ footprint

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#54]
MAX14930DASE+ is in narrow package, not wide.

From [datasheet](https://datasheets.maximintegrated.com/en/ds/MAX14130-MAX14932.pdf):
![image](https://user-images.githubusercontent.com/1595938/204641035-75b10198-a362-40d9-a85c-2fe5c7ceb146.png)

From Altium Designer component properties:
![image](https://user-images.githubusercontent.com/1595938/204641378-94c6d74c-732b-4026-b230-2e29bfe23de5.png)

**Comment by markus-marandi** [comment]
done
