### ISSUE TITLE
Improve component placement

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#55]
1. Divide PCB into two parts:
    * microcontroller and everything connected to it;
    * motor drivers and related components.
\
Something like this:
![image](https://user-images.githubusercontent.com/1595938/204725786-2fbab45c-7840-4130-88c5-8a890ef65c67.png)

3. Place components that connect to each other close to each other.
\
ESD protection needs to be as close as possible to USB connector, otherwise ESD spikes will reach other components before ESD protection.
![image](https://user-images.githubusercontent.com/1595938/204726157-40a075c1-d99f-42a0-8c0d-39f596481e34.png)
\
It's better to place USB connector close to microcontroller, instead of routing long tracks across the PCB.
![image](https://user-images.githubusercontent.com/1595938/204726407-61c25ef3-2001-4c3a-b280-c56046199de3.png)
\
Decoupling capacitors should be placed as close as possible to power supply pins of a component. Shorter connections have less inductance.
![image](https://user-images.githubusercontent.com/1595938/204726736-c1d3f21f-6f77-4df4-959e-4339985c0378.png)

**Comment by ReikoR** [comment]
1. Isolator rotated incorrectly. Microcontroller side signals are on the other side.
![image](https://user-images.githubusercontent.com/1595938/205439547-fc97b761-9b51-4867-8583-a679c11a1e14.png)
![image](https://user-images.githubusercontent.com/1595938/205439568-32164500-998d-43c8-9546-c3cbb619e30f.png)

2. Thrower connector needs to be on the motor drivers side.
![image](https://user-images.githubusercontent.com/1595938/205439680-7d2b92d5-072d-4ef4-aa36-5a6f03ed4f10.png)

3. Place decoupling capacitors close to supply pins on the same layer as the component.
![image](https://user-images.githubusercontent.com/1595938/205439761-723303dc-9d9d-4302-a648-3c140fbd1038.png)

**Comment by markus-marandi** [comment]
1. rotated isolator
2. moved thrower connector
3. replaced decoupling capacitors
4. replaced esd protection 
5. moved and rotated programmer connector
