### ISSUE TITLE
Make PCB smaller

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#58]
Try to make the PCB 50 x 50 mm or smaller as it's the cheapest option from JLCPCB.

![image](https://user-images.githubusercontent.com/1595938/204729633-d24272b5-30ae-4319-ab70-fe0995090438.png)

**Comment by markus-marandi** [comment]
done

**Comment by ReikoR** [comment]
PCB can be made smaller.

**Comment by markus-marandi** [comment]
new dimensions are 40x40
