### ISSUE TITLE
Switches and power plugs covered by PC

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#59]
The computers chassis covers the switches and sockets:

![image](https://user-images.githubusercontent.com/5435954/204870119-5b873d54-42d7-4a4c-9c1f-2b221589cb6d.png)

Also refer to this page for desired hole sizes:

https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_pc_power_adapter_socket

**Comment by ToxaRyd** [comment]
Yep, those are bad, I decided to make them 3d printed and attached to the bottom plate!

**Comment by Akustav** [comment]
The current switches can be triggered by an opponent or ball. If you dont have room I suggest putting them here: 
![image](https://user-images.githubusercontent.com/5435954/205147016-e584fb32-40e1-4176-81fd-6b4725dc5fa7.png)

**Comment by ToxaRyd** [comment]
Those switches are too big, putting them there will jeopardize the camera holder leg seriously (at least it does not seem reliable, and I don't like those things) But I will think on where else to put those

**Comment by ToxaRyd** [comment]
Actually, I am a lazy ass, so I decided to make as you said, but the charging port remains on the holder 3d printed plate. Please check if it is ok...

**Comment by maidlam** [comment]
Make the cutouts for the switch holes like this (from the guide).
If the hole is too thick, then the clips on the sides of the switches wont engage and the switch can come out.

![pilt](https://user-images.githubusercontent.com/32770145/205510788-a2a33f4c-4d0d-4726-a063-27283ae25b7e.png)

**Comment by ToxaRyd** [comment]
> Make the cutouts for the switch holes like this (from the guide). If the hole is too thick, then the clips on the sides of the switches wont engage and the switch can come out.
> 
> ![pilt](https://user-images.githubusercontent.com/32770145/205510788-a2a33f4c-4d0d-4726-a063-27283ae25b7e.png)

the hole is 4.8mm, but the part is one. meaning that on both parts manufactured the whole gonna be from on side only. So this thing will be done manualy

**Comment by maidlam** [comment]
Why make them by hand?
They only need a pocket and contour operation from one side, which the CNC can cut out quickly.

**Comment by ToxaRyd** [comment]
> Why make them by hand? They only need a pocket and contour operation from one side, which the CNC can cut out quickly.

The part gonna be then asymmetrical, I will need to do two walls' models. And I cannot do this cut from both sides...

**Comment by maidlam** [comment]
> I don't think there gonna be any problems with reaching the other side of the plate...
The switch can reach the other side, but it wont be in place correctly, because the clips wont engage.

> I will need to do two walls' models
You can make one of them and then create a mirror body with the mirror feature.

**Comment by ToxaRyd** [comment]
done
