### ISSUE TITLE
[Mechanics] Thrower and ramp are not centered

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#6]
Is this intended, that the thrower and internal ramp don't have the same center point? The further the ball travels in the thrower, the less it is accelerated by the motor.

![image](https://user-images.githubusercontent.com/5435954/193414154-09b07a0c-ad10-405c-aacd-83acb03ca985.png)

**Comment by ToxaRyd** [comment]
Yep, I was suggested that the first contact with the ball should have the motor, and only after the ramps

**Comment by Akustav** [comment]
Hm okay... I would suggest to reduce the delta a little, currently it is around 9.5mm:

![image](https://user-images.githubusercontent.com/5435954/194744031-dc60e1d7-a1ca-4b2b-afdf-d12e88e8312a.png)

You might remove acceleration potential by reducing contact pressure so fast.

**Comment by ToxaRyd** [comment]
Have decreased this distance by 3mm if I am not mistaken....resolved
