### ISSUE TITLE
Suggest making cable routing hole bigger

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#60]
I suggest making the hole for cable routing bigger since every bullet of D=3.5mm needs to fit in there while other cables are already in there. Also consider the internal corner radius when milling.

![image](https://user-images.githubusercontent.com/5435954/204870622-b8ec2bab-5bed-4e35-9295-2cbc11714a0c.png)

**Comment by ToxaRyd** [comment]
Done
