### ISSUE TITLE
Remove 3rd isolator

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#61]
![image](https://user-images.githubusercontent.com/1595938/205439092-4e526b23-d046-45ee-94a7-0335ff2e6630.png)

* SERVO PWM signal is not used.
* Motor driver DRVOFF pin can be connected to GND to have drivers enabled. It's probably not needed for the microcontroller to turn off the motor drivers.

**Comment by markus-marandi** [comment]
removed 3rd isolator
