### ISSUE TITLE
Motor driver capacitor footprint incorrect

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#62]
![image](https://user-images.githubusercontent.com/1595938/205440290-bee88b99-e571-4ebf-b6e4-4b20adbd80b2.png)

It seems to be for 1608 (1.6x0.8mm) metric package (0603 imperial), not 0805 imperial package (2012 metric).

**Comment by markus-marandi** [comment]
where can I validate if the footprints are updated with this measuring tool? Updated all the motor driver capacitor footprints.
