### ISSUE TITLE
Route USB data signals as differential pair

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#63]
More information here:
https://github.com/ut-robotics/picr22-team-gibibot/issues/32

## But use JLC7628 stackup as it is cheaper.

For example 8 mil (about 0.2 mm) trace space and 10.28 mil (about 0.26 mm) trace width would work:
![image](https://user-images.githubusercontent.com/1595938/200866780-67b5dbe1-dd22-4750-97ff-ab60f1978ab8.png)

**Comment by markus-marandi** [comment]
routed usb as differential pair

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205484739-6cefee7a-ef39-4405-a4fa-772b73654a68.png)

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205484752-7fa8ae06-baa2-4887-8e76-38c0df03532b.png)

**Comment by ReikoR** [comment]
Straighten the tracks:
![image](https://user-images.githubusercontent.com/1595938/205839669-22974ccf-e40b-4c39-a751-a1a380925217.png)

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205841506-17da823a-3c05-4235-818e-89bd84598dfe.png)
