### ISSUE TITLE
Gap between BUK6Y10-30P drain pads

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#64]
![image](https://user-images.githubusercontent.com/1595938/205440491-ce88c304-57a3-4a48-9d23-969e11d63792.png)

Try to get rid of the gap or just use one pad for drain.

**Comment by markus-marandi** [comment]
![image](https://user-images.githubusercontent.com/75824680/205484935-9204ad9c-9c53-4266-b383-aa89c8191e12.png)

![image](https://user-images.githubusercontent.com/75824680/205484998-56af3e94-4712-4857-9694-3da0374c8c90.png)

PCB editor still shows a cap, when its corrected from library and updated

**Comment by ReikoR** [comment]
Which library are you using?

 It's not in the repository.

![image](https://user-images.githubusercontent.com/1595938/205491612-474151a7-1782-42ab-9a46-2a2169a0e289.png)

**Comment by markus-marandi** [comment]
added library to repository
