### ISSUE TITLE
Incorrect CM1223-02SO footprint

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#65]
![image](https://user-images.githubusercontent.com/1595938/205440652-a3e33ca2-634e-4e48-912b-356ed5474db4.png)

CM1223-02SO is in SOT23-5 package, which has a pin pitch of 0.95mm.

From [datasheet](https://www.onsemi.com/pdf/datasheet/cm1223-d.pdf):
![image](https://user-images.githubusercontent.com/1595938/205440686-151a4ba3-42f2-4a1f-af8e-c13e7caeabff.png)
![image](https://user-images.githubusercontent.com/1595938/205440729-5b57c5aa-b53d-401d-ba92-9e89c6f8b27d.png)

**Comment by markus-marandi** [comment]
done
