### ISSUE TITLE
Avoid committing unnecessary files

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#66]
1. Delete `__Previews`, `History`, `Project Logs for picr22-team-snax-mainboard` directories and `*.LOG` files.
2. Create `.gitignore` file in `picr22-team-snax-mainboard` directory with following comment.
```
*.LOG
__Previews/
History/
```
3.  Commit `.gitignore` file and deleted files.

**Comment by markus-marandi** [comment]
done
