### ISSUE TITLE
Vias too small

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#68]
Minimum vias size should be 0.2 mm hole / 0.45 mm diameter.

From https://jlcpcb.com/capabilities/pcb-capabilities:
> For Multi Layer PCB, the minimum via hole size is 0.2mm
> For Multi Layer PCB, the minimum via diameter is 0.45mm

Some vias have diameter of 0.4 mm:
![image](https://user-images.githubusercontent.com/1595938/205840129-d98564fb-7d4e-41ed-bd7a-f346e0363388.png)

**Comment by markus-marandi** [comment]
done
