### ISSUE TITLE
[Mechanics] Interference in thrower-chassis assembly

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-snax#7]
There is clipping here:

![image](https://user-images.githubusercontent.com/5435954/194744310-95f02ca4-7154-4744-bb97-22319a9fb78a.png)

Is this intentional or a fault?

**Comment by ToxaRyd** [comment]
yeah, thats was because model of that robots and its actual sizes are not the same. I took those from the real one, will try to fix that

**Comment by ToxaRyd** [comment]
resolved but there are distance mistakes in the assembly of the robot itself, can show those somehow on practice session
