### ISSUE TITLE
Avoid placing reference designators underneath components

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-snax#70]
Reference designators should be visible when components have been soldered on the PCB.

![image](https://user-images.githubusercontent.com/1595938/205841531-7d644de9-a5b7-4ca1-b056-ee41757120ce.png)
![image](https://user-images.githubusercontent.com/1595938/205841701-ca6c88d0-f020-4e54-86c4-12c4d800aa57.png)

**Comment by markus-marandi** [comment]
done
